## load data

In [3]:
pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [17]:
from collections import Counter
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import california_housing

In [5]:
from sklearn.datasets import load_boston
from sklearn.datasets import load_digits
data = load_boston()
#data = load_digits()
datas = data['data']
targets = data['target']

In [18]:
c = Counter(targets)

[(50.0, 16), (25.0, 8), (21.7, 7), (23.1, 7), (22.0, 7)]

## test my_knn

In [2]:
%run kn_classifier.py
from model_selection import train_test_split
from metrics import accuracy_score
from preprocessing import StandardScaler
#from sklearn.preprocessing import StandardScaler

ImportError: attempted relative import with no known parent package

In [11]:
counts = datas.shape[0]
loops = 20
test_ratio = 0.2
my_knn = KNclassifier(5,weights='uniform')
ss = StandardScaler()

In [12]:
results = []
for _ in np.arange(loops):
    
    train_x ,test_x,train_y,test_y = train_test_split(datas,targets,test_ratio=test_ratio,seed=66)
    ss.fit(train_x)
    s_train_x = ss.transform(train_x)
    s_test_x= ss.transform(test_x)
    
    my_knn.fit(s_train_x,train_y)
    #predictions = my_knn.predict(test_x)

    accuracy = my_knn.score(s_test_x,test_y)
    results.append(accuracy)

print('average accuracy of knn: ', np.mean(results))

average accuracy of knn:  0.02970297029702971


In [14]:
whos

Variable           Type              Data/Info
----------------------------------------------
Counter            type              <class 'collections.Counter'>
KNclassifier       type              <class '__main__.KNclassifier'>
StandardScaler     type              <class 'preprocessing.StandardScaler'>
accuracy           float64           0.0297029702970297
accuracy_score     function          <function accuracy_score at 0x1157b75f0>
counts             int               506
data               Bunch             {'data': array([[6.3200e-<...>boston_house_prices.csv'}
datas              ndarray           506x13: 6578 elems, type `float64`, 52624 bytes
knn                function          <function knn at 0x115818950>
load_boston        function          <function load_boston at 0x1145cc290>
load_digits        function          <function load_digits at 0x1145cc0e0>
loops              int               20
my_knn             KNclassifier      <__main__.KNclassifier object at 0x1157c5b90>
n

## test myknn_regressor

In [36]:
%run kn_regressor.py
from model_selection import train_test_split
from metrics import r2_score
from preprocessing import StandardScaler

In [37]:
counts = datas.shape[0]
loops = 20
test_ratio = 0.2
my_knn = KNRegressor(5,weights='distance')
ss = StandardScaler()

In [40]:
results = []
for _ in np.arange(loops):
    
    train_x ,test_x,train_y,test_y = train_test_split(datas,targets,test_ratio=test_ratio)
    ss.fit(train_x)
    s_train_x = ss.transform(train_x)
    s_test_x= ss.transform(test_x)
    
    my_knn.fit(s_train_x,train_y)
    #predictions = my_knn.predict(test_x)

    #accuracy = accuracy_score(test_y,predictions)
    accuracy = my_knn.score(s_test_x,test_y)
    results.append(accuracy)

print('average error of knn: ', np.mean(results))

average error of knn:  0.8129891209408775


## test my linear_regressor

In [35]:
%run linear_regressor.py
from model_selection import train_test_split
from metrics import r2_score
from preprocessing import StandardScaler

loops = 10
test_ratio = 0.2
my_linear_reg = LinearRegressor()
ss = StandardScaler()

datas = datas[targets<50]
targets = targets[targets<50]

In [39]:
results =[]
for _ in np.arange(loops):
    
    train_x ,test_x,train_y,test_y = train_test_split(datas,targets,test_ratio=test_ratio)
    ss.fit(train_x)
    s_train_x = ss.transform(train_x)
    s_test_x = ss.transform(test_x)
    my_linear_reg.fit_gd(s_train_x,train_y)
    #my_linear_reg.fit_normal(s_train_x,train_y)
    errors = my_linear_reg.score(s_test_x,test_y)
    results.append(errors)

print('average error of linear regressor: ', np.mean(results))

    

average error of linear regressor:  0.7449601405805827


In [26]:
np.hstack([np.ones((10,1)),np.arange(10).reshape(10,1)])

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.],
       [1., 7.],
       [1., 8.],
       [1., 9.]])

In [47]:
ss = StandardScaler()
ss.fit(datas)

In [51]:
my_linear_reg.fit(ss.transform(datas),targets)
coef1 = my_linear_reg.coef_
my_linear_reg.fit(datas,targets)
coef2 = my_linear_reg.coef_

In [55]:
inx = np.argsort(np.abs(coef1))

In [57]:
inx = inx[::-1]

In [58]:
inx

array([ 4,  5,  7, 10, 12,  3,  8,  0,  2,  1,  6,  9, 11])

In [62]:
data.feature_names[inx[:5]],np.sign(coef1[inx[:5]])

(array(['NOX', 'RM', 'DIS', 'PTRATIO', 'LSTAT'], dtype='<U7'),
 array([-1.,  1., -1., -1., -1.]))

## sklearn 

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

In [4]:
knn_classifier = KNeighborsClassifier()

In [7]:
params = [{'weights':['uniform'],'n_neighbors':[i for i in np.arange(3,11)]},{'weights':['distance'],'n_neighbors':[i for i in np.arange(3,11)],'p':[i for i in np.arange(1,5)]}]

In [8]:
params

[{'weights': ['uniform'], 'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10]},
 {'weights': ['distance'],
  'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10],
  'p': [1, 2, 3, 4]}]

In [9]:

grid_search = GridSearchCV(knn_classifier,params,n_jobs=-1,verbose=2)

In [10]:
%%time 
grid_search.fit(datas,targets)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


/usr/local/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    8.3s


CPU times: user 377 ms, sys: 78.9 ms, total: 456 ms
Wall time: 57.3 s


[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:   57.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=-1,
       param_grid=[{'weights': ['uniform'], 'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10]}, {'weights': ['distance'], 'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10], 'p': [1, 2, 3, 4]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=2)

In [14]:
grid_search.best_score_


0.9682804674457429

## 梯度下降